### ISSUE TITLE
Files Rightclick missing

### ISSUE THREAD

**Issue by Luticus** [PaulLereverend/NextcloudExtract#10] opened 2019-04-29 17:45 UTC
Menu options shows on the ... menu but it is missing on the files rightclick menu.  Noticed it since this version.  I used to be there on previous versions.  I'm using nc16 and the lastest version of both your app and files rightclick.

**Comment by PaulLereverend** [comment] 2019-04-29 20:03
I do have it with the latest version. Could you try to clear your cache and reload ?

**Comment by Schmuuu** [comment] 2019-04-29 20:10
Hi,

I can confirm the issue and clearing the cache doesn't solve the problem.

Three dot menu:
![grafik](https://user-images.githubusercontent.com/26191454/56923610-4af53500-6acb-11e9-8f4a-bad436a7d0b1.png)

right click:
![grafik](https://user-images.githubusercontent.com/26191454/56923676-711ad500-6acb-11e9-854d-2794292a9158.png)

I don't see any logs messages directing to an issue.
It worked with the test version you provided before.

**Comment by PaulLereverend** [comment] 2019-04-29 20:30
You are right, it's working on my main instance but not on my dev one... but they are both exactly the same. Since I have the bug I can work on fixing it. I'll run more tests tomorrow and i'll keep you updated.

**Comment by PaulLereverend** [comment] 2019-04-30 18:32
Hi, 

I've done some research and it appears that the issue come from the RightClick app which has been referenced here : https://github.com/nextcloud/files_rightclick/issues/61 

The version with the fix is not yet available on the appstore but I cloned it and it worked. 

About why it appear just now, I think it's because of the update to NC 16 wich broke the rightclick and the update of the app which refreshed some cache and shows the problem. I've not changed anything related to the menu on the latest version. 

I also tried on NC 15 with extract 1.2 and Right Click 0.13 (both latest) and everything worked fine. 

I will keep this issue open as long as it is not resolved but all we can do is wait for the appstore release of the RC app.

**Comment by paulrolandw** [comment] 2019-05-03 12:02
Hey guys I am having the same issue, NC 16.

**Comment by Flipback8** [comment] 2019-05-30 17:03
any way to not have to click on the three dots and just right click directly on file to display the extract option?

**Comment by PaulLereverend** [comment] 2019-11-01 12:39
Fixed in NC 17

**Closed by PaulLereverend** 2019-11-01 12:39 UTC

**Comment by ioscanner** [comment] 2024-08-02 19:19
This seems to still be broken.  I have tried on NC 29 and 29.0.1
